### ISSUE TITLE
Deleting a task or note displays toast: "… konnte nicht gefunden werden"

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [deftkHD/OpenWebWeaver-Android#5]
Deleting a [task|note] from the corresponding read_[task|note] fragment, displays a toast. E.g. deleting a task shows: `Aufgabe "1064653" konnte nicht gefunden werden`.

**Comment by deftk** [comment]
Fixed with https://github.com/deftkHD/OpenWebWeaver-Android/commit/9caab678ff9003f6297455f45f8e7928eb6056d3
